export const SOCIAL_LANDING_DEFAULTS = {
  id: 'main',
  enabled: true,
  eyebrow: 'IDEALTECH · MADE IN ITALY',
  title: 'Industrial adhesive application, made easier.',
  subtitle: 'Hot-melt systems & equipment',
  description: 'Engineering · Support · Spare parts',
  logo_url: '/logo-cerchio.png',
  background_image_url: '',
  background_color: '#0b2d53',
  secondary_color: '#123f72',
  accent_color: '#5db8e9',
  card_color: '#ffffff',
  text_color: '#ffffff',
  button_text_color: '#12345c',
  show_made_in_italy: true,
  footer_text: 'Idealtech S.r.l. · Varedo, Italy',
}

export const SOCIAL_LINK_DEFAULTS = [
  {
    id: 'fallback-website',
    label: 'Sito web',
    subtitle: 'Scopri Idealtech',
    url: '/',
    icon_key: 'website',
    active: true,
    featured: false,
    new_tab: false,
    sort_order: 10,
    background_color: '',
    text_color: '',
  },
  {
    id: 'fallback-linkedin',
    label: 'LinkedIn',
    subtitle: 'Segui gli aggiornamenti aziendali',
    url: 'https://www.linkedin.com/company/idealtech-srl/',
    icon_key: 'linkedin',
    active: true,
    featured: false,
    new_tab: true,
    sort_order: 20,
    background_color: '',
    text_color: '',
  },
  {
    id: 'fallback-facebook',
    label: 'Instagram',
    subtitle: 'Prodotti, applicazioni e novità',
    url: 'https://www.instagram.com/idealtech.srl/',
    icon_key: 'instagram',
    active: true,
    featured: false,
    new_tab: true,
    sort_order: 30,
    background_color: '',
    text_color: '',
  },
  {
    id: 'fallback-contacts',
    label: 'Contatti',
    subtitle: 'Parla con il nostro team',
    url: '/contatti',
    icon_key: 'contact',
    active: true,
    featured: true,
    new_tab: false,
    sort_order: 40,
    background_color: '',
    text_color: '',
  },
]

export const SOCIAL_ICON_OPTIONS = [
  ['website', 'Sito web'],
  ['linkedin', 'LinkedIn'],
  ['facebook', 'Facebook'],
  ['instagram', 'Instagram'],
  ['whatsapp', 'WhatsApp'],
  ['email', 'Email'],
  ['phone', 'Telefono'],
  ['contact', 'Contatti'],
  ['support', 'Assistenza'],
  ['catalog', 'Catalogo / Prodotti'],
  ['download', 'Download'],
  ['map', 'Posizione'],
  ['external', 'Link esterno'],
]
